---
plugin: aws_ec2
# Populate inventory with instances in these regions
regions:
  - ap-southeast-2
filters:
  tag:Project: JRMonitor
keyed_groups:
  - prefix: Monitor # prefix is 'Monitor_'
    key: tags['Group'] # the Name tag can be 'main' or 'exporter'
hostnames:
  - tag:Name
    # so the groups are Monitor_main and Monitor_exporter