global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'Prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'Exporters'
    scrape_interval: 5s
    static_configs:
      - targets:
        - prometheus:9100
        - Exporter1_IP:9100
        - Exporter2_IP:9100

  - job_name: 'Containers'
    scrape_interval: 10s
    static_configs:
      - targets:
        - prometheus:8080
        - Exporter1_IP:8080
        - Exporter2_IP:8080

  - job_name: 'Jenkins'
    scrape_interval: 5s
    metrics_path: /prometheus/
    static_configs:
      - targets: ['MyJenkinsServer']